name: CI Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Remove node_modules and dist folders
        run: |
          rm -rf node_modules
          rm -rf dist

      - name: Install backend dependencies
        run: npm install

      - name: Run backend tests
        run: npm run test

      - name: Build backend
        run: npm run build

  frontend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Remove node_modules and dist folders
        run: |
          rm -rf node_modules
          rm -rf dist

      - name: Install frontend dependencies
        run: npm install

      - name: Run frontend tests
        run: echo "No frontend tests to run for now"

      - name: Build frontend
        run: npm run build
