name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    env:
      PORT: 3000
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      FRONTEND_MODE: dev
      FRONTEND_DEV_URL: http://localhost:5173

      VITE_MODE: dev
      VITE_DEV_BASE_BACKEND_URL: http://localhost:3000/api

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Install backend dependencies
        working-directory: backend
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Verify environment variables
        run: |
          echo "PORT: $PORT"
          echo "VITE_MODE: $VITE_MODE"

      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
